name: the_gorgeous_login
description: Gorgeous Login UI

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: 3.0.7
  firebase_auth: ^0.14.0+5
  connectivity: ^0.4.3+2
  wifi: ^0.1.5
  shared_preferences: ^0.5.3+4
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.1+4
  firebase_storage: ^3.0.6
  flutter_progress_button: '^1.0.0'
  sqflite: ^1.1.6+5
  path: ^1.6.4
  path_provider: ^1.4.3
  cloud_firestore: ^0.13.0+1
  loading: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1
  test: any
  e2e: ^0.2.0

flutter:

  uses-material-design: true

  assets:
      - assets/img/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
